### ISSUE TITLE
头部视图

### ISSUE THREAD

**Issue by 2020zy** [codingZero/XRWaterfallLayout#2]
怎么添加头部视图，怎么添加不起

**Comment by codingZero** [comment]
@2020zy 这个貌似是collectionView的问题吧，跟我的布局类没有关系啊😂

**Comment by 2020zy** [comment]
但是使用了你这个，头部视图协议方法加不上了 显示不出来

**Comment by 2020zy** [comment]
你在你的项目中 可以添加一个collection头部视图吗

**Comment by codingZero** [comment]
@2020zy  稍等，我看看

**Comment by 2020zy** [comment]
恩 加上了 给我说一声哈 谢谢

**Comment by codingZero** [comment]
研究了下，好像真的改不了😂

**Comment by codingZero** [comment]
@2020zy 研究了下，好像真的改不了😂

**Comment by 2020zy** [comment]
显示不出来了吗？你想办法解决一下撒，为什么不走协议方法了

**Comment by 2020zy** [comment]
那我想加一个头部视图怎么加呢

**Comment by codingZero** [comment]
@2020zy 我知道是什么原因，但是我没发改，有个协议方法是设置头部视图尺寸的- (CGSize)collectionView:(UICollectionView _)collectionView layout:(UICollectionViewLayout_)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section;只有设置了尺寸才会显示，但是这个方法是UICollectionViewFlowLayout的协议方法，而我的瀑布流是继承UICollectionViewLayout的，所以如果要改的话，所有的东西都要改，这没办法弄，不好意思了！
